# config file version
apiVersion: 1
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
# list of datasources to insert/update depending
# whats available in the database
datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true

  # Loki datasource
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100  # Adjust the URL according to your Loki setup
    isDefault: false  # Set to true if you want Loki as the default datasource
    jsonData:
      maxLines: 1000  # Adjust other Loki-specific configuration options
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true
